// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const migrationUrl =
  process.env["PRISMA_DATABASE_URL"] ??
  process.env["POSTGRES_URL_NON_POOLING"] ??
  process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use a direct connection for migration/introspection commands.
    // Keep application runtime connection independent (see app/lib/prisma.ts).
    url: migrationUrl,
  },
});
